### ISSUE TITLE
Model relationship

### ISSUE THREAD

**Issue by ehamrin** [mi222ep/1DV450_mi222ep#7]
Det känns inte som att modellförhållandet är kopplat korrekt åt båda hållen. Apikey tillhör en User (fungerar), men en User har flera Applications(?!), borde vara Apikeys

**Comment by mi222ep** [comment]
Haha. Det låg kvar sedan gammalt. Jag började att kalla klassen apikey för application. Vilket inte var särskilt bra, eftersom det ju redan finns en applicationController.
